"""initial schema

Revision ID: b54f507aa6c7
Revises:
Create Date: 2026-04-20 13:07:16.943560

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b54f507aa6c7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "environment", name="uq_flag_name_env"),
    )
    with op.batch_alter_table("feature_flag", schema=None) as batch_op:
        batch_op.create_index("ix_flag_environment", ["environment"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature_flag", schema=None) as batch_op:
        batch_op.drop_index("ix_flag_environment")

    op.drop_table("feature_flag")
    # ### end Alembic commands ###
